### PR TITLE
Add necessary methods for tsvd

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by jakebolewski** [comment]
Cool!  Add the tsvd as an example in the README?

**Comment by andreasnoack** [comment]
Yes. I'm halfway through an update of the README, but wanted to try this out on C3DDB

**Comment by poulson** [comment]
:100:

**Comment by jakebolewski** [comment]
Yes the expository example has to start with `addprocs(5_000)`...

**Pull request merged**
